# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyUSB0
baud: 9600
timeout: 1

rate: 50
sensorstate_rate: 10

use_base_controller: True
base_controller_rate: 10

# === Robot drivetrain parameters
wheel_diameter: 0.065
wheel_track: 0.16
encoder_resolution: 10
gear_reduction: 1.0
motors_reversed: True

# === PID parameters
Kp: 4
Ki: 100
Kd: 1

accel_limit: 1.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  ir_front:      {pin: 0, type: GP2D12, rate: 10},
  sonar_left:   {pin: 9, type: Ping, rate: 10},
  sonar_right:  {pin: 8, type: Ping, rate: 10},
  sonar_front:  {pin: 12, type: Ping, rate: 10},
  arduino_led:          {pin: 13, type: Digital, rate: 5, direction: output}
}
